version: "3.9"
services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/rtdto
      REDIS_URL: redis://redis:6379/0
  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.core.celery_app worker --pool=solo --loglevel=info
    depends_on:
      - redis
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/rtdto
      REDIS_URL: redis://redis:6379/0

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rtdto

    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_queue

    ports:
      - "6379:6379"